- name: /etc/resolv.confコピー
  template:
    src: "{{ TPF_bas_resolv }}"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: /etc/profileコピー
  template:
    src: "{{ TPF_bas_proxy }}"
    dest: /etc/environment
    owner: root
    group: root
    mode: 0644

- name: /etc/yum.confコピー
  template:
    src: "{{ TPF_bas_yumconf }}"
    dest: /etc/yum.conf
    owner: root
    group: root
    mode: 0644

- name: Reboot the machine (Wait for 5 min)
  reboot:
    reboot_timeout: 300
    


