- name: Install remi-release-7
  yum: name=https://repo.ius.io/ius-release-el7.rpm

- name: Install remi-release-7
  yum: name={{ item }}
  with_items:
    - python36u
    - python36u-pip
    - python36u-devel
    
    
- name: set default ruby version
  shell: pip3.6 install django


- name: set default ruby version
  shell: pip3.6 install --upgrade pip