---
- name: 「機器一覧」メニューからデータを取得(検索条件：備考欄)
  uri:
    url: "http://127.0.0.1/default/menu/07_rest_api_ver1.php?no=2100000303"
    validate_certs: no
    method: POST
    headers:
      Host: "127.0.0.1:80"
      Authorization: "cmVzdHVzZXI6cGFzc3dvcmQK"
      Content-Type: "application/json"
      X-Command: "FILTER"
    body_format: json
    body:
      "1":
        "NORMAL": "0"
  environment:
    - no_proxy: "127.0.0.1"
  register: device_list_from_exastro

- name: 取得したデータからレコード情報を抽出
  set_fact:
    device_list_from_exastro_body: "{{ device_list_from_exastro.json.resultdata.CONTENTS.BODY }}"


- name: 最終更新日時のカラム番号取得
  set_fact:
    _lastchangeTime: "{{ item.0 }}"
  with_indexed_items:
    - "{{ device_list_from_exastro_body.0 }}"
  when:
    item.1 == "更新用の最終更新日時"

- name: body成型
  set_fact:
    _rest_body: >-
      {%- set tmplist = [] -%}
      {%- for valloop in device_list_from_exastro_body -%}
      {%-   if loop.index > 1 -%}
      {%-     set tmpdic = {} -%}
      {%-     for val in valloop -%}
      {%-       if loop.index0 == 0 -%}
      {%-         set _ =  tmpdic.update( { loop.index0: "更新" }) -%}
      {%-       elif device_list_from_exastro_body[0][loop.index0] == "Ansible利用情報/接続オプション" -%}
      {%-         set _ =  tmpdic.update( { loop.index0: '-o ProxyCommand="ssh -W %h:%p -o \'StrictHostKeyChecking=no\' -i /root/id_rsa ' + VAR_ita_user + '@' + VAR_ita_host + ' 22" -o \'StrictHostKeyChecking=no\' -i /root/id_rsa -o \'StrictHostKeyChecking=no\'' }) -%}
      {%-       else -%}
      {%-         set _ =  tmpdic.update( { loop.index0: val }) -%}
      {%-       endif -%}
      {%-     endfor -%}
      {%-     set _ =  tmplist.append(tmpdic) -%}
      {%-   endif -%}
      {%- endfor -%}
      {{ tmplist }}
      

- debug:
    msg: "{{ item }}"
  loop:
    - "{{ _rest_body }}"


- name: 
  uri:
    url: "http://127.0.0.1/default/menu/07_rest_api_ver1.php?no=2100000303"
    validate_certs: no
    method: POST
    headers:
      Host: "127.0.0.1:80"
      Authorization: "cmVzdHVzZXI6cGFzc3dvcmQK"
      Content-Type: "application/json"
      X-Command: "EDIT"
    body_format: json
    body:
      "0":
        "{{ item }}"
  environment:
    - no_proxy: "127.0.0.1"
  when:
    - item.5 == "192.168.10.1"  or item.5 == "192.168.10.2" or item.5 == "192.168.20.1"or item.5 == "192.168.20.2"
  with_items:
    - "{{ _rest_body }}"