#【概要】 Terraform実行でVMware上にVMを作成するまえに、vCenterからVM一覧を取得する。
#【目的】 取得したリストは、「今回の実行で作成したVM」だけを機器一覧へ登録するために用いる。

- name: vSphereから取得した仮想マシンフォルダにあるVMの一覧を取得
  community.vmware.vmware_vm_info:
    hostname: "{{ VAR_vcenter_hostname }}"
    username: "{{ VAR_vcenter_username }}"
    password: "{{ VAR_vcenter_password }}"
    validate_certs: false
    folder: "{{ VAR_vSphere_datacenter_name }}/vm/{{ VAR_vSphere_folder_name }}"
  delegate_to: localhost
  register: fetch_vm_list_result
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: 実行後
  set_fact:
    vm_list_after_tf_apply: "{{ fetch_vm_list_result.virtual_machines }}"