#【概要】 Terraform実行でVMware上にVMを作成するまえに、vCenterからVM一覧を取得する。
#【目的】 取得したリストは、「今回の実行で作成したVM」だけを機器一覧へ登録するために用いる。


- name: vSphereから取得した仮想マシンフォルダにあるVMの一覧を取得
  community.vmware.vmware_vm_info:
    hostname: "{{ VAR_vcenter_hostname }}"
    username: "{{ VAR_vcenter_username }}"
    password: "{{ VAR_vcenter_password }}"
    validate_certs: false
    folder: "{{ VAR_vSphere_datacenter_name }}/vm/{{ VAR_vSphere_folder_name }}"
  delegate_to: localhost
  register: fetch_vm_list_result
  vars:
    ansible_python_interpreter: /usr/bin/python3
  failed_when: no


- name: Terrafrom実行前のVM一覧をconductor_workflowdirに配置。Terraform実行後に読み取る。
  blockinfile:
    create: yes
    mode: 644
    insertbefore: EOF
    marker: ""
    dest: "{{ __conductor_workflowdir__ }}/vm_list_before_tf_apply.yml"
    content: |
      vm_list_before_tf_apply: {{ (fetch_vm_list_result.virtual_machines is defined) | ternary(fetch_vm_list_result.virtual_machines, '[]', '[]') }}
  delegate_to: 127.0.0.1
