- name: VMware用Ansibleモジュールをダウンロード
  get_url:
    url: https://raw.githubusercontent.com/ansible-collections/community.vmware/1.17.0/requirements.txt
    dest: "{{ __workflowdir__ }}/requirements.txt"
    mode: '0644'
    force_basic_auth: no
  delegate_to: localhost
  
- name: VMware用Ansibleモジュールの要求ライブラリ一覧をダウンロード
  get_url:
    url: https://galaxy.ansible.com/download/community-vmware-1.17.0.tar.gz
    dest: "{{ __workflowdir__ }}/community-vmware-1.17.0.tar.gz"
    mode: '0644'
    force_basic_auth: no
    timeout: 180
  delegate_to: localhost

- name: VMware用Ansibleモジュールのインストール
  shell: "/usr/local/bin/ansible-galaxy collection install {{ __workflowdir__ }}/community-vmware-1.17.0.tar.gz"
  delegate_to: localhost

- name: VMware用Ansibleモジュールの要求ライブラリをインストール
  pip:
    requirements: "{{ __workflowdir__ }}/requirements.txt"
  delegate_to: localhost