- name: Install remi-release-7
  yum: name=https://repo.ius.io/ius-release-el7.rpm

- name: Install remi-release-7
  yum: name={{ item }}
  with_items:
    - python36u
    - python36u-pip
    - python36u-devel

- name: djangoのインストール
  shell: pip3.6 install django

- name: 取得可能な最新のpipをインストール
  shell: pip3.6 install --upgrade pip